### ISSUE TITLE
Match any output name

### ISSUE THREAD

**Issue by coredump** [emersion/kanshi#9]
So I have kanshi output:

```console
Connected outputs:
output DP-8 vendor DEL product Dell S2417DG serial YNY1D8140HMU
output DP-6 vendor ACI product VG248 serial H5LMQS083427
output eDP-1 vendor SHP product 0x1476 serial 0x0
Matching configuration: None
```

And this is my config

```console
{
  output DP-8 vendor DEL product Dell S2417DG serial YNY1D8140HMU resolution 2560x1440 position 1920,0
  output DP-6 vendor ACI product VG248 serial H5LMQS083427 resolution 1920x1080 position 0,0
  output eDP-1 vendor SHP product 0x1476 serial 0x0 resolution 3840x2160 scale 2 position 4480,0
}
```

Initially I thougth it was because my ports keep changing. I have tried without the port names, and also using the same syntax I use for sway outputs. None match anything.

**Comment by emersion** [comment]
I thought this was supported but I guess it isn't.

This would require adding a new feature: `output *` to be able to match any output name.

**Comment by emersion** [comment]
This config should now work:

```
{
  output * vendor DEL product Dell S2417DG serial YNY1D8140HMU resolution 2560x1440 position 1920,0
  output * vendor ACI product VG248 serial H5LMQS083427 resolution 1920x1080 position 0,0
  output eDP-1 vendor SHP product 0x1476 serial 0x0 resolution 3840x2160 scale 2 position 4480,0
}
```

**Comment by coredump** [comment]
So, I tried using the latest kanshi by installing it directly from the git repo and it still doesn't like the config:

```console
[I] ❯  kanshi                    
Connected outputs:
output eDP-1 vendor SHP product 0x1476 serial 0x0
output DP-4 vendor DEL product Dell S2417DG serial YNY1D8140HMU
output DP-5 vendor ACI product VG248 serial H5LMQS083427
Matching configuration: None
Waiting for output changes...
^C
                                                                                                                               
~ took 2s 
[I] ✘130 ❯  cat ~/.config/kanshi/config
{
  output * vendor DEL product Dell S2417DG serial YNY1D8140HMU resolution 2560x1440 position 1920,0
  output * vendor ACI product VG248 serial H5LMQS083427 resolution 1920x1080 position 0,0
  output eDP-1 vendor SHP product 0x1476 serial 0x0 resolution 3840x2160 scale 2 position 4480,0
}
```
